<aside class="aside-left">
    <div class="aside-content">
        <p><img src="images/logo-anl-badge.png"></p>
        <div>

            <h3>Auto New Life <br>
            ZA de Lacré<br>
            30700 Foissac</ph3>
            <h3><i class="fas fa-mobile-alt"></i> 06 33 35 33 61</h3>
            <p>autonewlife.contact@gmail.com</p>
            <p><i class="fas fa-envelope"></i>FORMULAIRE DE CONTACT</a></p>
        </div>
        <p><a href="" class="btn-red">Je demande un devis</a></p>
    </div>
    <img class="img-cadre" src="images/cadre-inv.png" alt="">
    <div class="social">
        <a href=""><img src="images/picto-fb.png" alt="icone facebook"></a>
        <a href=""><img src="images/picto-insta.png" alt="icone instagram"></a>
    </div>
</aside>