<main class="main-base">
    <div class="bg-covert">
        <h1>Mécanique</h1>
    </div>
    <section class="row max btw">
    <?php include 'asideLeft.phtml';?>
        
        <div id="contact" class="container col ard">
            <article>
                <h2>Contactez nous facilement</h2>
                <p>Quelque soit votre besoin : carrosserie, peinture, mécanique .... <br>
                une question ? un devis ? un rendez-vous ? <br>
                Ce formulaire est là pour ça. <br>
                Merci de nous donner le plus de précisions possibles sur votre demande.</p>
            </article>
            <article>
                <h3>Informations relatives aux données collectées</h3>
                <p>Les informations recueillies sur ce formulaire sont enregistrées dans un fichier informatisé par Auto New Life à des fins de communication uniquement suite à votre demande de devis ou toute autre demande d'informations. <br>
                Les données collectées seront communiquées aux seuls destinataires suivants : Auto New Life. <br>
                Les données seront conservées pendant la durée du traitement de votre demande et ne seront nullement utilisées à des fins commerciales ou transmises à des tiers. Vous pouvez accéder aux données vous concernant, les rectifier, demander leur effacement ou exercer votre droit à la limitation du traitement de vos données par simple demande.</p>
            </article>
            <article>
                <h2>Formulaire de contact</h2>
                <label for="last-name">Nom</label>
                <input type="text" name="last-name" id="last-name">
                <label for="first-name">Prénom</label>
                <input type="text" name="first-name" id="first-name">
                <label for="email">Mail</label>
                <input type="text" name="email" id="email">
                <label for="validate-email">Validez votre email</label>
                <input type="text" name="validate-email" id="validate-email">
                <label for="phone">Téléphone</label>
                <input type="text" name="phone" id="phone">
                <label for="adresse">Adresse</label>
                <input type="text" name="adresse" id="adresse">
                <label for="city">Ville</label>
                <input type="text" name="city" id="city">
                <label for="zip-code">Code Postal</label>
                <input type="text" name="zip-code" id="zip-code">
                <label for="message">Votre Message</label>
                <textarea name="message" id="message" cols="60" rows="10"></textarea>

            </article>
        </div>
        
        <?php include 'asideRight.phtml';?>
    </section>
</main>